### ISSUE TITLE
gcloud:deploy fails : ToolException: Could not synchronize files. The gsutil command exited with status [1]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#532]
```
What steps will reproduce the problem?

mvn clean install
mvn gcloud:deploy -Dgcloud.version=version1 -Dgcloud.gcloud_project=myproject


What is the expected output? What do you see instead?

expect to finish deploy 
I see the following :

[INFO] Uploading   ....com/e8dbc91b1d5c0d6e37f201b897dd5a003dd680cd.js: 0 
B/51.84 KiB    
[INFO] Uploading   ....com/e8dbc91b1d5c0d6e37f201b897dd5a003dd680cd.js: 51.84 
KiB/51.84 KiB    
[INFO] CommandException: 3 files/objects could not be copied/removed.
[INFO] INFO: Error synchronizing files. Return code: 1. Retrying.
[INFO] DEBUG: Running command: [/bin/bash 
/home/tareq/google-cloud-sdk/bin/gsutil -m rsync -R -c /tmp/tmpofq2NO 
gs://staging.tradeos-test1.appspot.com/], Env: [None]
[INFO] 
[INFO] WARNING: You have requested checksumming but your crcmod installation 
isn't
[INFO] using the module's C extension, so checksumming will run very slowly. 
For help
[INFO] installing the extension, please see:
[INFO]   $ gsutil help crcmod
[INFO] 
[INFO] Building synchronization state...
[INFO] Caught non-retryable exception while listing file:///tmp/tmpofq2NO: 
[Errno 2] No such file or directory: 
'/tmp/tmpofq2NO/babfa40c84b6077baf7352fbefd86de948e26b3c.pem'
[INFO] At destination listing 10000...
[INFO] At destination listing 20000...
[INFO] CommandException: Caught non-retryable exception - aborting rsync
[INFO] INFO: Error synchronizing files. Return code: 1. Retrying.
[INFO] DEBUG: Running command: [/bin/bash 
/home/tareq/google-cloud-sdk/bin/gsutil -m rsync -R -c /tmp/tmpofq2NO 
gs://staging.tradeos-test1.appspot.com/], Env: [None]
[INFO] 
[INFO] WARNING: You have requested checksumming but your crcmod installation 
isn't
[INFO] using the module's C extension, so checksumming will run very slowly. 
For help
[INFO] installing the extension, please see:
[INFO]   $ gsutil help crcmod
[INFO] 
[INFO] Building synchronization state...
[INFO] Caught non-retryable exception while listing file:///tmp/tmpofq2NO: 
[Errno 2] No such file or directory: 
'/tmp/tmpofq2NO/babfa40c84b6077baf7352fbefd86de948e26b3c.pem'
[INFO] At destination listing 10000...
[INFO] At destination listing 20000...
[INFO] CommandException: Caught non-retryable exception - aborting rsync
[INFO] INFO: Error synchronizing files. Return code: 1. Retrying.
[INFO] DEBUG: Running command: [/bin/bash 
/home/tareq/google-cloud-sdk/bin/gsutil -m rsync -R -c /tmp/tmpofq2NO 
gs://staging.tradeos-test1.appspot.com/], Env: [None]
[INFO] 
[INFO] WARNING: You have requested checksumming but your crcmod installation 
isn't
[INFO] using the module's C extension, so checksumming will run very slowly. 
For help
[INFO] installing the extension, please see:
[INFO]   $ gsutil help crcmod
[INFO] 
[INFO] Building synchronization state...
[INFO] Caught non-retryable exception while listing file:///tmp/tmpofq2NO: 
[Errno 2] No such file or directory: 
'/tmp/tmpofq2NO/babfa40c84b6077baf7352fbefd86de948e26b3c.pem'
[INFO] At destination listing 10000...
[INFO] At destination listing 20000...
[INFO] CommandException: Caught non-retryable exception - aborting rsync
[INFO] INFO: Error synchronizing files. Return code: 1. Retrying.
[INFO] DEBUG: (gcloud.preview.app.deploy) Could not synchronize files. The 
gsutil command exited with status [1]
. Command output is available in 
[/home/tareq/.config/gcloud/logs/2016.02.09/20.18.20.168000.log].
[INFO] Traceback (most recent call last):
[INFO]   File 
"/home/tareq/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 609, in 
Execute
[INFO]     result = args.cmd_func(cli=self, args=args)
[INFO]   File 
"/home/tareq/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 
1228, in Run
[INFO]     resources = command_instance.Run(args)
[INFO]   File 
"/home/tareq/google-cloud-sdk/lib/googlecloudsdk/surface/preview/app/deploy.py",
 line 271, in Run
[INFO]     app_config.NonHermeticModules().items(), code_bucket)
[INFO]   File 
"/home/tareq/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/deploy_app_command_
util.py", line 66,
 in CopyFilesToCodeBucket
[INFO]     s=e.last_result, l=log.GetLogFilePath()))
[INFO] ToolException: Could not synchronize files. The gsutil command exited 
with status [1]. Command output is 
available in [/home/tareq/.config/gcloud/logs/2016.02.09/20.18.20.168000.log].
[INFO] ERROR: (gcloud.preview.app.deploy) Could not synchronize files. The 
gsutil command exited with status [1]
. Command output is available in 
[/home/tareq/.config/gcloud/logs/2016.02.09/20.18.20.168000.log].


What is the output of 'gcloud info'?

Google Cloud SDK [91.0.1]

Platform: [Linux, x86_64]
Python Version: [2.7.6 (default, Jun 22 2015, 17:58:13)  [GCC 4.8.2]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/home/tareq/google-cloud-sdk]
Installed Components:
  core: [2015.12.16]
  app-engine-python: [1.9.30]
  core-nix: [2015.11.24]
  app-engine-java: [1.9.30]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.16]
  bq: [2.0.18]
  bq-nix: [2.0.18]
System PATH: 
[/home/tareq/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/
bin:/sbin:/bin:/usr
/games:/usr/local/games:/opt/apache-maven-3.3.9/bin]
Cloud SDK on PATH: [True]
Installation Properties: [/home/tareq/google-cloud-sdk/properties]
User Config Directory: [/home/tareq/.config/gcloud]
User Properties: [/home/tareq/.config/gcloud/properties]
Current Workspace: [None]
Workspace Config Directory: [None]
Workspace Properties: [None]
Account: [tareq@freightos.com]
Project: [tradeos-test1]
Current Properties:
  [core]
    project: [tradeos-test1]
    account: [tareq@freightos.com]
    disable_usage_reporting: [True]
  [app]
    promote_by_default: [false]
    stop_previous_version: [false]
    use_appengine_api: [true]
    use_cloud_build: [false]
    suppress_change_warning: [true]
  [compute]
    region: [us-central1]
    zone: [us-central1-f]
Logs Directory: [/home/tareq/.config/gcloud/logs]
Last Log File: [/home/tareq/.config/gcloud/logs/2016.02.09/20.18.20.168000.log]


Please provide any additional information below.

im executing these command on ubuntu14.04 LTS on VM instance on project1 to 
deploy the app on another vm instance on myproject


```

Original issue reported on code.google.com by `ta...@freightos.com` on 9 Feb 2016 at 8:43

**Comment by GoogleCodeExporter** [comment]
```
please note that project1= tradeos-test2 and myproject=tradeos-test1
```

Original comment by `ta...@freightos.com` on 9 Feb 2016 at 8:47

**Comment by GoogleCodeExporter** [comment]
```
Do you mind sharing the contents of 
/home/tareq/.config/gcloud/logs/2016.02.09/20.18.20.168000.log ?
```

Original comment by `z...@google.com` on 10 Feb 2016 at 10:08
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
We think we have this issue diagnosed and will be updating with any new 
developments.
```

Original comment by `z...@google.com` on 17 Feb 2016 at 5:10
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Any updates on this? We're being affected by this as well. Multiple python/js 
projects.
```

Original comment by `r...@ave81.com` on 24 Feb 2016 at 8:57

**Comment by GoogleCodeExporter** [comment]
```
This issue will be fixed in the to-be-released 99.0.0 version of gcloud.
```

Original comment by `z...@google.com` on 24 Feb 2016 at 9:00

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 24 Feb 2016 at 9:00
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Until then, is there anything we can do? It seems to only happen on some 
projects and not others. I notice it happens on projects that have a lot of 
files. Any connection?
```

Original comment by `r...@ave81.com` on 24 Feb 2016 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
Can you try running with:

  $ gcloud config set app/use_cloud_build true

? It's a new hosted build service that should be more reliable.
```

Original comment by `z...@google.com` on 24 Feb 2016 at 10:51

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Same problem. 

File 
"/etc/gcloud/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/deploy_app_command_
util.py", line 66, in CopyFilesToCodeBucket
```

Original comment by `r...@ave81.com` on 25 Feb 2016 at 12:03

**Comment by GoogleCodeExporter** [comment]
```
That flag didn't seem to change the way it acts. I did:

  $ gcloud config set app/use_cloud_build true

... then as normal

  $ gcloud preview app deploy test.yaml --verbosity debug --version 0-17-59 --configuration center

But the verbose output is identical. So that config option didn't seem to have 
any effect. I even enabled the API in that project for the Google Cloud 
Container Builder API


```

Original comment by `r...@ave81.com` on 25 Feb 2016 at 12:15

**Comment by GoogleCodeExporter** [comment]
```
Are you still seeing this with the 98.0.0 version of gcloud? We fixed a related 
error recently.
```

Original comment by `z...@google.com` on 25 Feb 2016 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
I'm still seeing this error. But only on a computer which i guess has a user 
folder with spaces och and & in the name, could that be the issue?
The same command works on other computers which doesn't have a setup like that:
gcloud --project=hv-match preview app deploy -q app.yaml --verbosity debug


INFO: Error synchronizing files. Return code: 1. Retrying.
DEBUG: Running command: [cmd /c C:\Program Files (x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\gsutil.cmd -m rsync -R -c 
c:\users\hanna&~1\appdata\local\temp\tmptblirg 
gs://staging.hv-match.appspot.com/]]
DEBUG: Executing command: ['cmd', '/c', 'C:\\Program Files (x86)\\Google\\Cloud 
SDK\\google-cloud-sdk\\bin\\gsutil.cmd', '-m', 'rsync', '-R', '-c', 
'c:\\users\\hanna&~1\\appdata\\local\\temp\\tmptblirg', 
'gs://staging.hv-match.appspot.com/']
INFO: Error synchronizing files. Return code: 1. Retrying.
DEBUG: (gcloud.preview.app.deploy) Could not synchronize files. The gsutil 
command exited with status [1]. Command output is available in [C:\Users\Hanna 
& Markus\AppData\Roaming\gcloud\logs\2016.02.26\11.47.45.591000.log].


The real path is C:\Users\Hanna & Markus\... but it tries to run the command 
with c:\users\hanna&~1\...
Could that be an issue?
```

Original comment by `margor...@gmail.com` on 26 Feb 2016 at 10:57

**Comment by GoogleCodeExporter** [comment]
```
"c:\users\hanna&~1\" is the equivalent short file name format on Windows, so 
this should not be an issue. Is this still occurring for you on the current 
gcloud version 103.0.0?
```

Original comment by `araf...@google.com` on 3 Apr 2016 at 10:17
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Yes: 

Copying files to Google Cloud Storage...
Synchronizing files to [staging.hv-match.appspot.com].
DEBUG: Running command: [cmd /c C:\Program Files (x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\gsutil.cmd -m rsync -R -c 
c:\users\hanna&~1\appdata\local\temp\tmpsy3j1x 
gs://staging.hv-match.appspot.com/]]
DEBUG: Executing command: ['cmd', '/c', 'C:\\Program Files (x86)\\Google\\Cloud 
SDK\\google-cloud-sdk\\bin\\gsutil.cmd', '-m', 'rsync', '-R', '-c', 
'c:\\users\\hanna&~1\\appdata\\local\\temp\\tmpsy3j1x', 
'gs://staging.hv-match.appspot.com/']
INFO: Error synchronizing files. Return code: 1. Retrying.

DEBUG: Running command: [cmd /c C:\Program Files (x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\gsutil.cmd -m rsync -R -c 
c:\users\hanna&~1\appdata\local\temp\tmpsy3j1x 
gs://staging.hv-match.appspot.com/]]
DEBUG: Executing command: ['cmd', '/c', 'C:\\Program Files (x86)\\Google\\Cloud 
SDK\\google-cloud-sdk\\bin\\gsutil.cmd', '-m', 'rsync', '-R', '-c', 
'c:\\users\\hanna&~1\\appdata\\local\\temp\\tmpsy3j1x', 
'gs://staging.hv-match.appspot.com/']
INFO: Error synchronizing files. Return code: 1. Retrying.

DEBUG: Running command: [cmd /c C:\Program Files (x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\gsutil.cmd -m rsync -R -c 
c:\users\hanna&~1\appdata\local\temp\tmpsy3j1x 
gs://staging.hv-match.appspot.com/]]
DEBUG: Executing command: ['cmd', '/c', 'C:\\Program Files (x86)\\Google\\Cloud 
SDK\\google-cloud-sdk\\bin\\gsutil.cmd', '-m', 'rsync', '-R', '-c', 
'c:\\users\\hanna&~1\\appdata\\local\\temp\\tmpsy3j1x', 
'gs://staging.hv-match.appspot.com/']
INFO: Error synchronizing files. Return code: 1. Retrying.

DEBUG: Running command: [cmd /c C:\Program Files (x86)\Google\Cloud 
SDK\google-cloud-sdk\bin\gsutil.cmd -m rsync -R -c 
c:\users\hanna&~1\appdata\local\temp\tmpsy3j1x 
gs://staging.hv-match.appspot.com/]]
DEBUG: Executing command: ['cmd', '/c', 'C:\\Program Files (x86)\\Google\\Cloud 
SDK\\google-cloud-sdk\\bin\\gsutil.cmd', '-m', 'rsync', '-R', '-c', 
'c:\\users\\hanna&~1\\appdata\\local\\temp\\tmpsy3j1x', 
'gs://staging.hv-match.appspot.com/']
INFO: Error synchronizing files. Return code: 1. Retrying.

DEBUG: (gcloud.preview.app.deploy) Could not synchronize files. The gsutil 
command exited with status [1]. Command output is available in [C:\Users\Hanna 
& Markus\AppData\Roaming\gcloud\logs\2016.04.08\08.34.37.332000.log].
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\cli.py", line 654, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\surface\preview\app\deploy.py", line 522, in Run
    storage_client)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\app\deploy_app_command_util.py", line 233, in CopyFilesToCodeBucket
    s=e.last_result, l=log.GetLogFilePath()))
ToolException: Could not synchronize files. The gsutil command exited with 
status [1]. Command output is available in [C:\Users\Hanna & 
Markus\AppData\Roaming\gcloud\logs\2016.04.08\08.34.37.332000.log].
ERROR: (gcloud.preview.app.deploy) Could not synchronize files. The gsutil 
command exited with status [1]. Command output is available in [C:\Users\Hanna 
& Markus\AppData\Roaming\gcloud\logs\2016.04.08\08.34.37.332000.log].
```

Original comment by `margor...@gmail.com` on 8 Apr 2016 at 6:36

**Comment by GoogleCodeExporter** [comment]
```
margorjon: Can you try running this command again, with the setting `gcloud 
config set app/use_gsutil false`? It should avoid this code path (we plan to 
make this the default setting very soon).
```

Original comment by `z...@google.com` on 8 Apr 2016 at 8:28

**Comment by GoogleCodeExporter** [comment]
```
Well, at least it produced another error!


You are about to deploy the following modules:
 - hv-match/default (from [C:\Users\Hanna & Markus\Dropbox\GoogleApps\hv-match\app.yaml])
     Deployed URL: [https://hv-match.appspot.com]

Beginning deployment...
ERROR: gcloud crashed (MaxRetrialsException): last_result=(None, (<class 
'googlecloudsdk.calliope.exceptions.BadFileException'>, 
BadFileException('[C:\\Users\\Hanna & 
Markus\\Dropbox\\GoogleApps\\hv-match\\source-contexts.json] not found or not 
accessible',), <traceback object at 0x0429B0F8>)), last_retrial=3, 
time_passed_ms=0,time_to_wait=0

If you would like to report this issue, please run the following command:
  gcloud feedback
19:33
```

Original comment by `margor...@gmail.com` on 9 Apr 2016 at 5:35

**Comment by GoogleCodeExporter** [comment]
```
Thanks for updating. Can you attach the full stack trace from deployment now 
that you're getting this new error?
```

Original comment by `z...@google.com` on 11 Apr 2016 at 8:52

**Comment by GoogleCodeExporter** [comment]
```
I'm trying to reproduce the problem on a Windows machine. Since I strongly 
suspect you are correct it has something to do with the "&" in the directory 
name, I created my own directory with a similar name, but I find that mvn 
doesn't handle quoting properly for names containing "&" (spaces work fine).

It can't even find my pom.xml... Is there some trick you're using to get it to 
work?

```

Original comment by `danie...@google.com` on 12 Apr 2016 at 1:49

**Comment by GoogleCodeExporter** [comment]
```
The mvn issue is https://issues.apache.org/jira/browse/MNG-5962, which is fixed 
but won't be out till mvn 3.3.10.  I patched it locally on my machine, and was 
able to build and deploy even in a directory whose name included "&".

I think you may be hitting a bug that was just recently exposed when the 
default for app/use_gsutil was changed from true to false (in app-engine-java 
1.9.34, I believe). You should be able to work around the problem by going back 
to the old value with the command:

gcloud config set app/use_gsutil true

Please try that and let me know if it fixes the issue.

```

Original comment by `danie...@google.com` on 14 Apr 2016 at 12:06

**Comment by GoogleCodeExporter** [comment]
```
Let's use https://code.google.com/p/google-cloud-sdk/issues/detail?id=726 as 
the canonical issue here (for the BadFileException), and close this out, as the 
original issue has been made obsolete by the cloud_build changes..
```

Original comment by `z...@google.com` on 14 Apr 2016 at 1:51
- Changed state: **Obsolete**

**Comment by GoogleCodeExporter** [comment]
```
Sorry, this issue is not obsolete. But we'll use this to track the "gsutil 
command exited with status [1]" message and see which 

You can work around with `gcloud config set app/use_gsutil false` and moving 
your `.git` directory out of the current directory before deploying.
```

Original comment by `z...@google.com` on 14 Apr 2016 at 1:53
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
#19 Is this what you were asking for?



DEBUG: Running gcloud.preview.app.deploy with 
Namespace(__calliope_internal_deepest_parser=ArgumentParser(prog='gcloud.preview
.app.deploy', usage=None, description="*(BETA)* This command is used to deploy 
both code and configuration to the App Engine\nserver.  As an input it takes 
one or more ``DEPLOYABLES'' that should be\nuploaded.  A ``DEPLOYABLE'' can be 
a module's .yaml file or a configuration's\n.yaml file.", version=None, 
formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', 
add_help=False), account=None, authority_selector=None, 
authorization_token_file=None, bucket=None, cmd_func=<bound method Command.Run 
of <googlecloudsdk.calliope.backend.Command object at 0x03B46550>>, 
command_path=['gcloud', 'preview', 'app', 'deploy'], configuration=None, 
credential_file_override=None, deployables=['app.yaml'], docker_build=None, 
document=None, force=False, format=None, h=None, help=None, http_timeout=None, 
ignore_bad_certs=False, image_url=None, log_http=None, project='hv-match', 
promote=None, quiet=True, repo_info_file=None, server=None, 
stop_previous_version=True, trace_email=None, trace_log=None, trace_token=None, 
user_output_enabled=None, verbosity='debug', version='1').
DEBUG: API endpoint: [https://appengine.googleapis.com/], API version: [v1beta4]
You are about to deploy the following modules:
 - hv-match/default (from [C:\Users\Hanna & Markus\Dropbox\GoogleApps\hv-match\app.yaml])
     Deployed URL: [https://hv-match.appspot.com]

Beginning deployment...
DEBUG: No bucket specified, retrieving default bucket.
DEBUG: Using bucket [<googlecloudsdk.api_lib.app.cloud_storage.BucketReference 
object at 0x03B46630>].
INFO: Ignoring directory [.git]: Directory matches ignore regex.
DEBUG: Skipping upload of [HelveticaWorld-Regular.ttf]
DEBUG: Skipping upload of [_gcloud_init.bat]
DEBUG: Uploading [C:\Users\Hanna & 
Markus\Dropbox\GoogleApps\hv-match\source-contexts.json] to 
[0c3f21b2a2615c011efe3f631b28b8f7b5708ca8]
DEBUG: last_result=(None, (<class 
'googlecloudsdk.calliope.exceptions.BadFileException'>, 
BadFileException('[C:\\Users\\Hanna & 
Markus\\Dropbox\\GoogleApps\\hv-match\\source-contexts.json] not found or not 
accessible',), <traceback object at 0x048FB0F8>)), last_retrial=3, 
time_passed_ms=3,time_to_wait=0
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\cli.py", line 654, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\surface\preview\app\deploy.py", line 522, in Run
    storage_client)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\app\deploy_app_command_util.py", line 170, in CopyFilesToCodeBucketNoGsUtil
    _UploadFiles(files_to_upload, bucket_ref, storage_client)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\api_lib\app\deploy_app_command_util.py", line 113, in _UploadFiles
    args=(bucket_ref, path, sha1_hash, storage_client)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\util\retry.py", line 176, in RetryOnException
    TryFunc, should_retry_if=should_retry, sleep_ms=sleep_ms)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\util\retry.py", line 234, in RetryOnResult
    self._RaiseIfStop(result, state)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\lib\googlecloudsdk\core\util\retry.py", line 109, in _RaiseIfStop
    raise MaxRetrialsException('Reached', result, state)
MaxRetrialsException: last_result=(None, (<class 
'googlecloudsdk.calliope.exceptions.BadFileException'>, 
BadFileException('[C:\\Users\\Hanna & 
Markus\\Dropbox\\GoogleApps\\hv-match\\source-contexts.json] not found or not 
accessible',), <traceback object at 0x048FB0F8>)), last_retrial=3, 
time_passed_ms=3,time_to_wait=0
ERROR: gcloud crashed (MaxRetrialsException): last_result=(None, (<class 
'googlecloudsdk.calliope.exceptions.BadFileException'>, 
BadFileException('[C:\\Users\\Hanna & 
Markus\\Dropbox\\GoogleApps\\hv-match\\source-contexts.json] not found or not 
accessible',), <traceback object at 0x048FB0F8>)), last_retrial=3, 
time_passed_ms=3,time_to_wait=0

If you would like to report this issue, please run the following command:
  gcloud feedback
14:13

C:\Users\Hanna & Markus\Dropbox\GoogleApps\hv-match>
```

Original comment by `margor...@gmail.com` on 15 Apr 2016 at 12:15

**Comment by GoogleCodeExporter** [comment]
```
Perfect, thanks. Are you able to work around for now?

The issue with `gcloud config set app/use_gsutil false` will be fixed in the 
106.0.0 Cloud SDK release; that's the preferred option moving forward.
```

Original comment by `z...@google.com` on 15 Apr 2016 at 1:32

**Comment by GoogleCodeExporter** [comment]
```
Work around? What do you mean? :)
I can still not deploy, if that is what you are asking!
```

Original comment by `margor...@gmail.com` on 16 Apr 2016 at 8:47

**Comment by GoogleCodeExporter** [comment]
```
See #23:

You can work around with `gcloud config set app/use_gsutil false` and moving 
your `.git` directory out of the current directory before deploying.

```

Original comment by `z...@google.com` on 19 Apr 2016 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
Note that there were two issues here. The fix for the first issue was in build 
106, but the fix for the other issue is currently planned to be released next 
week (in build 108).
```

Original comment by `danie...@google.com` on 29 Apr 2016 at 1:17
