### ISSUE TITLE
Editor permissions role not enough for deploying to Managed VM Environment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#656]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
Make sure to first run "gcloud auth login" and choose an account that has only 
the Editor role in the Permissions section.
Then run "mvn gcloud:deploy" or "gcloud preview app deploy" for an app that's 
designated to the Standard VM environment.
I used an app in the Java 7 / Jetty 9.2 Compat environment.

What is the expected output? What do you see instead?
Expected same output as when deploying as an Owner.
Instead I got the below permissions error.

Please provide any additional information below.
Mac OS X Yosemite (10.10.5)
I used "mvn gcloud:deploy"
Deploying the same app to the Standard Google App Engine Environment worked 
great with Editor role. But failed for the Managed VM Environment. When 
switched to Owner, succeeded to Managed VM Environment.
Before running into this issue, I ran into another issue, that is solved as far 
as I'm concerned (issue #476).

Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk/third_party/apitools/base/py/base_api.py", line 714, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response))
  File "googlecloudsdk/third_party/apitools/base/py/base_api.py", line 586, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(http_response)
HttpError: HttpError accessing 
<https://cloudbuild.googleapis.com/v1/projects/myProject/builds?alt=json>: 
response: <{'status': '403', 'alternate-protocol': '443:quic,p=1', 
'content-length': '126', 'x-xss-protection': '1; mode=block', 
'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 
'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 
'cache-control': 'private', 'date': 'Tue, 15 Mar 2016 17:42:10 GMT', 
'x-frame-options': 'SAMEORIGIN', 'alt-svc': 'quic=":443"; ma=2592000; 
v="31,30,29,28,27,26,25"', 'content-type': 'application/json; charset=UTF-8'}>, 
content <{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
>

[output truncated]

```

Original issue reported on code.google.com by `yair.sh...@gmail.com` on 16 Mar 2016 at 11:12

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report. MVM issues are being tracked and worked on.
```

Original comment by `gsfow...@google.com` on 16 Mar 2016 at 2:59
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting! This is something that's already being worked on and 
tracked.

Without going into details (they're boring and involve some internal 
information), there's a good reason that you need OWNER permissions right now, 
but we have a solution in mind where you eventually won't.
```

Original comment by `z...@google.com` on 16 Mar 2016 at 3:57
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
OK, thanks for the update!
```

Original comment by `yair.sh...@gmail.com` on 16 Mar 2016 at 4:00
