### ISSUE TITLE
gcloud init crashed after I authorized in browser

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#657]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 654, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1376, in Run
    resources = command_instance.Run(args)
  File "surface/init.py", line 108, in Run
    if not self._PickAccount(args.console_only):
  File "surface/init.py", line 159, in _PickAccount
    disable_user_output=False):
  File "surface/init.py", line 439, in _RunCmd
    result = self.cli.Execute(args)
  File "googlecloudsdk/calliope/cli.py", line 654, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1376, in Run
    resources = command_instance.Run(args)
  File "googlecloudsdk/calliope/exceptions.py", line 110, in TryFunc
    return func(*args, **kwargs)
  File "surface/auth/login.py", line 135, in Run
    args.brief)
  File "surface/auth/login.py", line 150, in LoginAs
    client.save_to_well_known_file(google_creds)
  File "third_party/oauth2client/client.py", line 1277, in save_to_well_known_file
    raise OSError('Config directory does not exist: %s' % config_dir)
OSError: Config directory does not exist: 
/usr/local/google/home/yarbrough/.config/gcloud

Installation information:

Google Cloud SDK [HEAD]

Platform: [Linux, x86_64]
[output truncated]

```

Original issue reported on code.google.com by `yarbro...@google.com` on 16 Mar 2016 at 6:04

**Comment by GoogleCodeExporter** [comment]
```
Is this reproducible? I can't reproduce:

$ rm -rf ~/.config/gcloud
$ gcloud init
[...]
Created new window in existing browser session.
You are now logged in as: [...@...]

I tried this for several installation methods. How did you install the Cloud 
SDK (if it's a Google-internal method, please don't post it here; you can shoot 
me an email)?

```

Original comment by `z...@google.com` on 17 Mar 2016 at 4:20
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Can't reproduce this after offline discussions.
```

Original comment by `z...@google.com` on 17 Mar 2016 at 9:51
- Changed state: **WontFix**
