### ISSUE TITLE
Import error: No module named contrib.gce

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#659]
```
We are unable to install the new version of google-cloud-sdk, it throws No 
module named contrib.gce error

What steps will reproduce the problem?

1. Download https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip
2. extract and install 
export CLOUDSDK_PYTHON=#{python_dirname}/python
  ./install.sh --usage-reporting false --path-update false --command-completion false

What is the expected output? What do you see instead?

google cloud sdk should be installed properly, but I see the following error

STDOUT: Welcome to the Google Cloud SDK!
STDERR: Traceback (most recent call last):
  File "/opt/google-cloud-sdk/bin/bootstrapping/install.py", line 8, in <module>
    import bootstrapping
  File "/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 17, in <module>
    import oauth2client.contrib.gce as gce
ImportError: No module named contrib.gce


What is the output of 'gcloud info'?

gcloud info
Google Cloud SDK [101.0.0]

Platform: [Linux, x86_64]
Python Version: [2.7.7 (default, Jul 10 2015, 16:12:25)  [GCC 4.4.7 20120313 
(Red Hat 4.4.7-11)]]
Python Location: [/usr/local/bin/python2]
Site Packages: [Disabled]

Installation Root: [/opt/google-cloud-sdk]
Installed Components:
  core: [2016.03.11]
  core-nix: [2016.02.05]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.17]
  bq: [2.0.18]
  bq-nix: [2.0.18]




```

Original issue reported on code.google.com by `Kidanek...@gmail.com` on 16 Mar 2016 at 11:54

**Comment by GoogleCodeExporter** [comment]
```
I'm unable to reproduce this. What python distribution are you passing in as 
CLOUDSDK_PYTHON?
```

Original comment by `dlor...@google.com` on 18 Mar 2016 at 8:38
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Here is the python version used for CLOUDSDK_PYTHON

Python 2.7.9
```

Original comment by `Kidanek...@gmail.com` on 18 Mar 2016 at 11:40

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Issue 677 has been merged into this issue.
```

Original comment by `z...@google.com` on 22 Mar 2016 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
We have not been able to reproduce the issue which you have described. If 
others are able to reproduce this issue, please open a new issue which links to 
this issue and any posts where it was reproduced so we can take another look.
```

Original comment by `faiz...@google.com` on 6 Apr 2016 at 7:18
- Changed state: **NotReproducible**
