### ISSUE TITLE
gcloud dataproc jobs submit failed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#661]
```
Issue running command [gcloud dataproc jobs submit pyspark].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.

Traceback (most recent call last):
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gsutil.py", line 106, in RunMain
    sys.exit(gslib.__main__.main())
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 364, in main
    perf_trace_token=perf_trace_token)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 541, in _RunNamedCommandAndHandleExceptions
    parallel_operations, perf_trace_token=perf_trace_token)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 280, in RunNamedCommand
    return_code = command_inst.RunCommand()
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 958, in RunCommand
    fail_on_error=(not self.continue_on_error))
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1176, in Apply
    arg_checker, should_return_results, fail_on_error)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1247, in _SequentialApply
    worker_thread.PerformTask(task, self)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/command.py", line 1711, in PerformTask
    results = task.func(cls, task.args, thread_state=self.thread_gsutil_api)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 697, in _CopyFuncWrapper
    cls.CopyFunc(args, thread_state=thread_state)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/commands/cp.py", line 849, in CopyFunc
    gzip_exts=self.gzip_exts))
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 2841, in PerformCopy
    allow_splitting=allow_splitting)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 1618, in _UploadFileToObject
    dst_obj_metadata, preconditions, gsutil_api, logger)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/copy_helper.py", line 1369, in _UploadFileToObjectNonResumable
    provider=dst_url.scheme, fields=UPLOAD_RETURN_FIELDS)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 233, in UploadObject
    return self._GetApi(provider).UploadObject(
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 100, in _GetApi
    self._LoadApi(provider, api_selector)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 125, in _LoadApi
    perf_trace_token=self.perf_trace_token))
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 166, in __init__
    loaded_credentials = self._CheckAndGetCredentials(logger)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 290, in _CheckAndGetCredentials
    user_creds = self._GetOauth2UserAccountCreds()
  File "/Users/son69/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 337, in _GetOauth2UserAccountCreds
    boto.config).GetCredentials()
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/gcs-oauth2-boto-plugin/gcs_oauth2_boto_plugin/oauth2_client.py", line 578, in GetCredentials
    access_token = self.GetAccessToken()
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/gcs-oauth2-boto-plugin/gcs_oauth2_boto_plugin/oauth2_client.py", line 316, in GetAccessToken
    access_token = self.FetchAccessToken()
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/retry-decorator/retry_decorator/retry_decorator.py", line 20, in f_retry
    return f(*args, **kwargs)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/gcs-oauth2-boto-plugin/gcs_oauth2_boto_plugin/oauth2_client.py", line 599, in FetchAccessToken
    credentials.refresh(http)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/client.py", line 633, in refresh
    self._refresh(http.request)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/client.py", line 842, in _refresh
    self._do_refresh_request(http_request)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/client.py", line 874, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1570, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1317, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1290, in _conn_request
    conn.connect()
  File "/Users/son69/google-cloud-sdk/platform/gsutil/third_party/httplib2/python2/httplib2/__init__.py", line 1060, in connect
    raise socket.error, msg
socket.error: [Errno 65] No route to host

Installation information:

Google Cloud SDK [98.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/son69/google-cloud-sdk]
Installed Components:
  core: [2016.02.22]
  app-engine-python: [1.9.32]
  core-nix: [2016.02.05]
  kubectl: []
  app-engine-java: [1.9.32]
  gcloud: []
  gsutil-nix: [4.15]
  app-engine-php: [ ]
  gsutil: [4.16]
  bq: [2.0.18]
  app-engine-php-darwin: [2015.11.16]
  alpha: [2016.01.12]
  bq-nix: [2.0.18]
  kubectl-darwin-x86_64: [1.1.7]
System PATH: 
[/Users/son69/Documents/go_appengine:/usr/local/mysql/lib:/Users/son69/Library/A
ndroid/sdk/platform-tools:/Users/son69/google-cloud-sdk/bin:/usr/local/bin:/usr/
bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/son69/Go/bin:/usr/local/opt/go
/libexec/bin]
Cloud SDK on PATH: [True]

WARNING: There are old versions of the Google Cloud Platform tools on your 
system PATH.
  /Users/son69/Documents/go_appengine/dev_appserver.py

Installation Properties: [/Users/son69/google-cloud-sdk/properties]
User Config Directory: [/Users/son69/.config/gcloud]
User Properties: [/Users/son69/.config/gcloud/properties]
Current Workspace: [None]
[output truncated]

```

Original issue reported on code.google.com by `lnts1...@gmail.com` on 17 Mar 2016 at 6:18

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the report, and sorry to hear you had an issue. It looks like the 
error you hit is usually caused by network issues.  If you retry the command, 
does it work?
```

Original comment by `dlor...@google.com` on 18 Mar 2016 at 8:39
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
It worked. Thanks
```

Original comment by `lnts1...@gmail.com` on 21 Mar 2016 at 3:40
