### ISSUE TITLE
Crashed while deploying

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#662]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

The folder contains only two files, app.yaml and main.py (plus a virtualenv 
folder named 'env')

app.yaml:

#application: python-managed-vm
#version: 1
runtime: python-compat
vm: true
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.app

skip_files:
- (.idea/.*)
- (env/.*)
- (.vscode/.*)
- (docs/.*)
- ^(.*/)?.*\.pyc


main.py
import webapp2

class MainHandler(webapp2.RequestHandler):
    def get(self):
        self.response.write('Hello world!')

app = webapp2.WSGIApplication([
    ('/', MainHandler)
], debug=True)

What is the expected output? What do you see instead?

Certainly did not expect a crash. Also, obviously expected the app to actually 
be deployed.

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1394, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 483, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 200, in BuildAndPushDockerImages
    cli, version_id, remote, project) as docker_client:
  File "googlecloudsdk/api_lib/app/images/docker_util.py", line 237, in __enter__
    kwargs = containers.KwargsFromEnv(self._vm.host, self._vm.cert_dir, True)
  File "googlecloudsdk/api_lib/app/containers.py", line 100, in KwargsFromEnv
    assert_hostname=False)
  File "third_party/docker/docker/tls.py", line 46, in __init__
    'Path to a certificate and key files must be provided'
TLSParameterError: Path to a certificate and key files must be provided through 
the client_config param. TLS configurations should map the Docker CLI client 
configurations. See http://docs.docker.com/examples/https/ for API details.

Installation information:

Google Cloud SDK [98.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
[output truncated]

```

Original issue reported on code.google.com by `t...@slb.com` on 17 Mar 2016 at 2:33
- Merged into: #559

**Comment by GoogleCodeExporter** [comment]
```
Please upgrade your Cloud SDK installation: gcloud components update
```

Original comment by `z...@google.com` on 17 Mar 2016 at 2:35
- Changed state: **Duplicate**
