### ISSUE TITLE
gcloud crashes - about can;t use ssh from comsole

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#664]
```
What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "lib\googlecloudsdk\core\cli.py", line 135, in Http
    creds = c_store.Load()
  File "lib\googlecloudsdk\core\credentials\store.py", line 286, in Load
    Refresh(cred)
  File "lib\googlecloudsdk\core\credentials\store.py", line 304, in Refresh
    creds.refresh(http or _Http())
  File "bin\..\lib\third_party\oauth2client\client.py", line 604, in refresh
    self._refresh(http.request)
  File "bin\..\lib\third_party\oauth2client\client.py", line 787, in _refresh
    self._do_refresh_request(http_request)
  File "bin\..\lib\third_party\oauth2client\client.py", line 806, in _do_refresh_request
    self.token_uri, method='POST', body=body, headers=headers)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1308, in _conn_request
    response = conn.getresponse()
  File "C:\python27_x64\lib\httplib.py", line 1033, in getresponse
    raise ResponseNotReady()
ResponseNotReady

[output truncated]

```

Original issue reported on code.google.com by `Robert.B...@gmail.com` on 18 Mar 2016 at 1:14

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. ResponseNotReady indicates that we tried to connect 
to the Google services but didn't receive any response.

Are you behind a firewall or proxy? If you use a proxy for normal web browsing, 
we attempt to pick that up, but you may have to configure your proxy manually:

        gcloud config set proxy/address
        gcloud config set proxy/port
        gcloud config set proxy/type
        gcloud config set proxy/username
        gcloud config set proxy/password
```

Original comment by `z...@google.com` on 18 Mar 2016 at 11:42
- Changed state: **NeedsMoreInfo**
