### ISSUE TITLE
git push won't push, get failed auth eventually

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#666]
```
Issue running command [gcloud auth git].

What steps will reproduce the problem?
1. git push

What is the expected output? What do you see instead?
Expected:Commits are pushed.
Actual: 
$ git push
ERROR: gcloud crashed (BadStatusLine): ''

If you would like to report this issue, please run the following command:
  gcloud feedback
Username for 'https://source.developers.google.com': 

I then try my username and password, which don't seem to work.

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

[output truncated]

```

Original issue reported on code.google.com by `josh.dep...@gmail.com` on 19 Mar 2016 at 1:13

**Comment by GoogleCodeExporter** [comment]
```
BadStatusLine indicates a network error–do you have any unusual network 
settings? Are you behind a firewall or proxy? Do `gcloud` commands work?

Can you post the whole stacktrace? It printed out in your terminal when you ran 
`gcloud feedback`.
```

Original comment by `z...@google.com` on 20 Mar 2016 at 2:54
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Here's one of the logs with this error


```

Original comment by `josh.dep...@gmail.com` on 20 Mar 2016 at 5:09

Attachments:
- [18.11.46.189783.log](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-666/comment-2/18.11.46.189783.log)

**Comment by GoogleCodeExporter** [comment]
```
Is this issue reproducible? What percentage of the time does it happen?
```

Original comment by `z...@google.com` on 21 Mar 2016 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
It happened consistently, but I fixed it by rerunning gcloud init.
(Also, apologies for the lack of more investigation on my end, I'm
currently travelling.)
```

Original comment by `josh.dep...@gmail.com` on 21 Mar 2016 at 1:50

**Comment by GoogleCodeExporter** [comment]
```
No worries; glad you could work around.

We'll make sure that this gets a better error in the future.
```

Original comment by `z...@google.com` on 21 Mar 2016 at 3:16
- Changed state: **Accepted**
