### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#667]
```
Issue running command [gcloud init].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "surface/auth/login.py", line 121, in Run
    creds = self.DoInstalledAppBrowserFlow(launch_browser)
  File "surface/auth/login.py", line 168, in DoInstalledAppBrowserFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "googlecloudsdk/core/credentials/store.py", line 445, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 170, in Run
    credential = flow.step2_exchange(code, http=http)
  File "third_party/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "third_party/oauth2client/client.py", line 2000, in step2_exchange
    headers=headers)
  File "third_party/httplib2/__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "third_party/httplib2/__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "third_party/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "third_party/httplib2/__init__.py", line 1059, in connect
    raise SSLHandshakeError(e)
[output truncated]

```

Original issue reported on code.google.com by `alexis.t...@gmail.com` on 19 Mar 2016 at 12:02

**Comment by GoogleCodeExporter** [comment]
```
Hey,

Sorry to see you had an issue. It looks like your compute is having trouble 
connecting to the Google production servers. Are you able to browse to 
google.com or googleapis.com in your browser?
```

Original comment by `dlor...@google.com` on 19 Mar 2016 at 4:38
- Changed state: **NeedsMoreInfo**
