### ISSUE TITLE
Problem with Nodejs deployment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#670]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?
gcloud preview app deploy

What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 211, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 285, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\lib\third_party\docker\docker\api\build.py", line 97, in build
    timeout=timeout,
  File "bin\..\lib\third_party\docker\docker\client.py", line 107, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "bin\..\lib\third_party\requests\sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "bin\..\lib\third_party\requests\sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "bin\..\lib\third_party\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "bin\..\lib\third_party\requests\adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
[output truncated]

```

Original issue reported on code.google.com by `kelv....@gmail.com` on 20 Mar 2016 at 5:45

**Comment by GoogleCodeExporter** [comment]
```
Sorry to hear you had trouble. Could you please attach the full stack trace 
(which can be obtained from running "gcloud info --show-log")?
```

Original comment by `dlor...@google.com` on 22 Mar 2016 at 6:08
- Changed state: **NeedsMoreInfo**
