### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#675]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?

gcloud auth login

What is the expected output? What do you see instead?

Expected: Successfull login

Actually: ERROR: gcloud crashed (HTTPError): (503, 'Service Unavailable')

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk/core/credentials/store.py", line 445, in AcquireFromWebFlow
    http=_Http())
  File "googlecloudsdk/core/credentials/flow.py", line 170, in Run
    credential = flow.step2_exchange(code, http=http)
  File "third_party/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "third_party/oauth2client/client.py", line 2000, in step2_exchange
    headers=headers)
  File "third_party/httplib2/__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "third_party/httplib2/__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "third_party/httplib2/__init__.py", line 1272, in _conn_request
    conn.connect()
  File "third_party/httplib2/__init__.py", line 1033, in connect
    sock.connect((self.host, self.port))
  File "third_party/socks/__init__.py", line 442, in connect
    self.__negotiatehttp(destpair[0], destpair[1])
  File "third_party/socks/__init__.py", line 406, in __negotiatehttp
    raise HTTPError((statuscode, statusline[2]))
HTTPError: (503, 'Service Unavailable')

[output truncated]

```

Original issue reported on code.google.com by `roger.ma...@sonymobile.com` on 22 Mar 2016 at 2:36

**Comment by GoogleCodeExporter** [comment]
```
503 is usually a transient error–do you still get this if you try again?
```

Original comment by `z...@google.com` on 28 Mar 2016 at 6:01
- Changed state: **NeedsMoreInfo**
