### ISSUE TITLE
ImportError: No module named contrib.gce

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#677]
```
What steps will reproduce the problem?

Hard to reproduce - seemed to be transient. this was on a job that was run via 
cron every 15 minutes. 

What is the expected output? What do you see instead?

Just uses the bq command line tool to query, copy and create some tables. 

Error i got was:

Traceback (most recent call last):
File "/usr/bin/../lib/google-cloud-sdk/bin/bootstrapping/bq.py", line 10, in 
import bootstrapping
File "/usr/lib/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 17, 
in 
import oauth2client.contrib.gce as gce
ImportError: No module named contrib.gce


Please provide any additional information below.


```

Original issue reported on code.google.com by `andrew.m...@pmc.com` on 22 Mar 2016 at 7:31
- Merged into: #659

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 22 Mar 2016 at 7:32
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
application can run locally when Google App Engine Launcher is used.

But throws,

 > dev_appserver.py main.py

Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\dev_appserver.py", line 11, in <module>
    import bootstrapping.bootstrapping as bootstrapping
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\bootstrapping\bootstrapping.py", line 17, in <module>
    import oauth2client.contrib.gce as gce
ImportError: No module named contrib.gce

OS: windows 10
```

Original comment by `inboxdri...@gmail.com` on 18 Apr 2016 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
application can run locally when Google App Engine Launcher is used.

But throws,

 > dev_appserver.py main.py

Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\dev_appserver.py", line 11, in <module>
    import bootstrapping.bootstrapping as bootstrapping
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\bootstrapping\bootstrapping.py", line 17, in <module>
    import oauth2client.contrib.gce as gce
ImportError: No module named contrib.gce

OS: windows 10

* main.py in using flask
```

Original comment by `inboxdri...@gmail.com` on 18 Apr 2016 at 2:58
