### ISSUE TITLE
Please assist: deployment crashed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#679]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 215, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 289, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "lib\googlecloudsdk\api_lib\app\docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "bin\..\lib\third_party\docker\docker\api\build.py", line 49, in build
    context = utils.tar(path, exclude=exclude, dockerfile=dockerfile)
  File "bin\..\lib\third_party\docker\docker\utils\utils.py", line 86, in tar
    t.add(os.path.join(root, path), arcname=path, recursive=False)
  File "C:\python27\lib\tarfile.py", line 2000, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "C:\python27\lib\tarfile.py", line 1872, in gettarinfo
    statres = os.lstat(name)
WindowsError: [Error 3] The system cannot find the path specified: 
'C:\\Users\\gaurav\\nodejs-getting-started\\6-pubsub\\node_modules\\gcloud\\node
_modules\\gce-images\\node_modules\\google-auto-auth\\node_modules\\google-auth-
library\\node_modules\\gtoken\\node_modules\\google-p12-pem\\node_modules\\node-
forge\\tests\\forge_ssl\\forge\\__init__.py'

[output truncated]

```

Original issue reported on code.google.com by `gauravgu...@gmail.com` on 23 Mar 2016 at 10:09
- Merged into: #496

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 23 Mar 2016 at 12:58
- Changed state: **Duplicate**
