### ISSUE TITLE
Gcloud components update fails with Error 145

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#683]
```
Issue running command [gcloud components update].

What steps will reproduce the problem?

1. On Windows 10 with the command prompt running as administrator, type "gcloud 
components update"
2. During the update process, it displays the error message and stops.

What is the expected output? What do you see instead?

The expected output should be something like "update completed successfully."
Instead, it showed the following error message:
   ERROR: gcloud crashed (WindowsError): [Error 145] The directory is not empty: 'C:\\Program Files\\Google\\Cloud SDK\\google-cloud-sdk\\.install\\.backup\\platform\\google_appengine\\google\\appengine\\tools\\devappserver2'


Please provide any additional information below.

I run "gcloud components update" several times and all attempts failed.
I rebooted the computer and run the command and got the same result.



Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "googlecloudsdk\core\updater\local_state.py", line 469, in ClearBackup
    file_utils.RmTree(self.__backup_directory)
  File "googlecloudsdk\core\util\files.py", line 176, in RmTree
    shutil.rmtree(path, onerror=_HandleRemoveError)
  File "C:\python27_x64\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\python27_x64\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\python27_x64\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\python27_x64\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\python27_x64\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\python27_x64\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\python27_x64\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\python27_x64\lib\shutil.py", line 254, in rmtree
    os.rmdir(path)
[output truncated]

```

Original issue reported on code.google.com by `nobun....@gmail.com` on 25 Mar 2016 at 1:56

**Comment by GoogleCodeExporter** [comment]
```
This points to corruption in your Cloud SDK installation.

Can you try deleting "C:\Program Files\Google\Cloud 
SDK\google-cloud-sdk\.install\.backup" and try again? If that doesn't work, you 
can remove the "C:\Program Files\Google\Cloud SDK\google-cloud-sdk" and install 
fresh from http://cloud.google.com/sdk/
```

Original comment by `z...@google.com` on 25 Mar 2016 at 2:44
- Changed state: **NeedsMoreInfo**
