### ISSUE TITLE
Can't install gcloud

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#684]
```
Issue running command [gcloud components update].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 654, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1376, in Run
    resources = command_instance.Run(args)
  File "surface/components/update.py", line 96, in Run
    version=args.version)
  File "googlecloudsdk/core/updater/update_manager.py", line 748, in Update
    disable_backup = self._ShouldDoFastUpdate(allow_no_backup=allow_no_backup)
  File "googlecloudsdk/core/updater/update_manager.py", line 301, in _ShouldDoFastUpdate
    cwd = os.path.realpath(os.getcwd())
OSError: [Errno 2] No such file or directory

Installation information:

Google Cloud SDK [101.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.0 (clang-700.0.59.5)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/ludo/google-cloud-sdk]
Installed Components:
  core: [2016.03.11]
  app-engine-python: [1.9.34]
  core-nix: [2016.02.05]
  gcloud: []
  gsutil-nix: [4.15]
  gsutil: [4.17]
  bq: [2.0.24]
  bq-nix: [2.0.18]
System PATH: 
[/Users/ludo/google-cloud-sdk/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/
Users/ludo/google-cloud-sdk/bin]
[output truncated]

```

Original issue reported on code.google.com by `ludovic....@gmail.com` on 25 Mar 2016 at 3:48

**Comment by GoogleCodeExporter** [comment]
```
What directory are you in when you run this command? The message suggests that 
you have no current working directory; was it deleted? Can you reproduce this 
if you run the command from another directory?
```

Original comment by `z...@google.com` on 28 Mar 2016 at 6:00
- Changed state: **NeedsMoreInfo**
