### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#688]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk\calliope\cli.py", line 646, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk\calliope\backend.py", line 1402, in Run
    resources = command_instance.Run(args)
  File "surface\preview\app\deploy.py", line 300, in Run
    config_cleanup = configurator.GenerateConfigs()
AttributeError: 'NoneType' object has no attribute 'GenerateConfigs'

Installation information:

Google Cloud SDK [96.0.0]

Platform: [Windows, x86_64]
Python Version: [2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC 
v.1500 64 bit (AMD64)]]
Python Location: [C:\python27\python.exe]
Site Packages: [Disabled]

Installation Root: [C:\Users\Eray\AppData\Local\Google\Cloud 
SDK\google-cloud-sdk]
Installed Components:
  core: [2016.02.05]
  bq-win: [2.0.18]
  core-win: [2016.02.05]
  gcloud: []
  windows-ssh-tools: [2016.01.29]
  gsutil: [4.16]
  gsutil-win: [4.16]
  bq: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `erryan1988@gmail.com` on 28 Mar 2016 at 12:06
- Merged into: #544

**Comment by GoogleCodeExporter** [comment]
```
Please update to Cloud SDK version 99.0.0 or greater.
```

Original comment by `z...@google.com` on 28 Mar 2016 at 1:55
- Changed state: **Duplicate**
