### ISSUE TITLE
ERROR: gcloud crashed (error): [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#694]
```
What steps will reproduce the problem?
1. run gcloud compute ssh --project organika-777 bid-engine-app-01

What is the expected output? What do you see instead?
1. can login to bid-engine-app-01 compute engine
2. i saw the gcloud crash

Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 54] Connection reset by peer

[output truncated]

```

Original issue reported on code.google.com by `agus3win...@gmail.com` on 30 Mar 2016 at 5:14

**Comment by GoogleCodeExporter** [comment]
```
Was this a one time thing or does it happening often?
```

Original comment by `stephe...@google.com` on 31 Mar 2016 at 3:09
- Changed state: **NeedsMoreInfo**
