### ISSUE TITLE
Error "remote_api is not the name of a valid builtin" and an empty list of available handlers.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#696]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?
Expected to deploy successfully.  Instead, I get an error that "remote_api is 
not the name of a valid builtin" and an empty list for the available handlers.

Please provide any additional information below.


Traceback (most recent call last):
  File "/google/data/ro/teams/cloud-sdk/gcloud/google3/third_party/py/googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "/google/data/ro/teams/cloud-sdk/gcloud/google3/third_party/py/googlecloudsdk/calliope/cli.py", line 654, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/google/data/ro/teams/cloud-sdk/gcloud/google3/third_party/py/googlecloudsdk/calliope/backend.py", line 1390, in Run
    resources = command_instance.Run(args)
  File "/google/data/ro/teams/cloud-sdk/gcloud/google3/third_party/py/googlecloudsdk/surface/preview/app/deploy.py", line 398, in Run
  File "/google/data/ro/teams/cloud-sdk/gcloud/google3/third_party/py/googlecloudsdk/api_lib/app/yaml_parsing.py", line 334, in __init__
    if not self.__LoadYamlFile(f):
  File "/google/data/ro/teams/cloud-sdk/gcloud/google3/third_party/py/googlecloudsdk/api_lib/app/yaml_parsing.py", line 429, in __LoadYamlFile
    yaml = ModuleYamlInfo.FromFile(file_path)
  File "/google/data/ro/teams/cloud-sdk/gcloud/google3/third_party/py/googlecloudsdk/api_lib/app/yaml_parsing.py", line 220, in FromFile
    parsed = _YamlInfo._ParseYaml(file_path, appinfo_includes.Parse)
  File "/google/data/ro/teams/cloud-sdk/gcloud/google3/third_party/py/googlecloudsdk/api_lib/app/yaml_parsing.py", line 106, in _ParseYaml
    return parser(fp)
[output truncated]

```

Original issue reported on code.google.com by `d...@google.com` on 31 Mar 2016 at 6:56

**Comment by GoogleCodeExporter** [comment]
```
What's the app.yaml file you're using?

Can you post the complete stack trace? It appears to have been truncated.
```

Original comment by `z...@google.com` on 31 Mar 2016 at 7:11
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Nevermind, looks like a known issue with a locally built gcloud.par file using 
hermetic python.  `gcloud preview app` works as expected with the stable 
release channel.
```

Original comment by `d...@google.com` on 1 Apr 2016 at 8:37

**Comment by GoogleCodeExporter** [comment]
```
Thanks for following up.
```

Original comment by `z...@google.com` on 1 Apr 2016 at 8:56
- Changed state: **Invalid**
