### ISSUE TITLE
deploying app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#700]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "lib\googlecloudsdk\calliope\cli.py", line 643, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "lib\googlecloudsdk\calliope\backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "lib\surface\preview\app\deploy.py", line 350, in Run
    deploy_command_util.DoPrepareManagedVms(gae_client)
  File "lib\googlecloudsdk\api_lib\app\deploy_command_util.py", line 250, in DoPrepareManagedVms
    gae_client.PrepareVmRuntime()
  File "lib\googlecloudsdk\api_lib\app\appengine_client.py", line 198, in PrepareVmRuntime
    rpcserver.Send('/api/vms/prepare', app_id=self.project)
  File "lib\googlecloudsdk\api_lib\app\util.py", line 370, in Send
    response = self._server.Send(*args, **kwargs)
  File "lib\googlecloudsdk\third_party\appengine\tools\appengine_rpc_httplib2.py", line 230, in Send
    url, method=method, body=payload, headers=headers)
  File "bin\..\./lib\third_party\oauth2client\client.py", line 562, in new_request
    redirections, connection_type)
  File "bin\..\./lib\third_party\httplib2\__init__.py", line 1608, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "bin\..\./lib\third_party\httplib2\__init__.py", line 1350, in _request
[output truncated%5

```

Original issue reported on code.google.com by `kartitha...@gmail.com` on 3 Apr 2016 at 12:38

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this. Do you mind posting the whole stack trace? It should 
be included in the output when you run "gcloud feedback".
```

Original comment by `z...@google.com` on 4 Apr 2016 at 1:41
- Changed state: **NeedsMoreInfo**
