### ISSUE TITLE
not able to run gcloud happens once in a while

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#702]
```
Issue running command [gcloud auth login].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "lib\googlecloudsdk\gcloud_main.py", line 171, in main
    gcloud_cli.Execute()
  [...]
  File "lib\surface\auth\login.py", line 122, in Run
    creds = self.DoInstalledAppBrowserFlow(launch_browser)
  File "lib\surface\auth\login.py", line 168, in DoInstalledAppBrowserFlow
    return c_store.AcquireFromWebFlow(launch_browser=launch_browser)
  File "lib\googlecloudsdk\core\credentials\store.py", line 421, in AcquireFromWebFlow
    http=_Http())
  File "lib\googlecloudsdk\core\credentials\flow.py", line 170, in Run
    credential = flow.step2_exchange(code, http=http)
  File "bin\..\lib\third_party\oauth2client\util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "bin\..\lib\third_party\oauth2client\client.py", line 1993, in step2_exchange
    headers=headers)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1610, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1352, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "bin\..\lib\third_party\httplib2\__init__.py", line 1278, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
[output truncated]

```

Original issue reported on code.google.com by `spra...@gmail.com` on 3 Apr 2016 at 5:04

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your feedback and sorry about the delayed response.

Could you please provide the following additional information:
- Full output of `gcloud info` (removing any personal data)
- Full stacktrace

Looks like this may be a issue with your network configuration. Are you behind 
a proxy of some sort?

```

Original comment by `vil...@google.com` on 21 Apr 2016 at 4:25
- Changed state: **NeedsMoreInfo**
