### ISSUE TITLE
Error to deploy a custom env to App Engine (Ruby based)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#704]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

Run 'gcloud preview app deploy' to a custom ruby image

Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  [...]
  File "surface/preview/app/deploy.py", line 494, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 215, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 289, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "googlecloudsdk/api_lib/app/docker_image.py", line 110, in Build
    nocache=self._nocache, rm=self._rm, pull=False)
  File "third_party/docker/docker/api/build.py", line 97, in build
    timeout=timeout,
  File "third_party/docker/docker/client.py", line 107, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "third_party/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "third_party/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "third_party/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "third_party/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

[output truncated]

```

Original issue reported on code.google.com by `alvaro.i...@pinho.com.br` on 4 Apr 2016 at 2:36

Attachments:
- [Dockerfile](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-704/comment-0/Dockerfile)
- [app.yaml](https://storage.googleapis.com/google-code-attachments/google-cloud-sdk/issue-704/comment-0/app.yaml)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting this! It appears to be a network issue. Do you get the 
same behavior when you run again after setting `gcloud config set 
app/use_cloud_build true`?
```

Original comment by `z...@google.com` on 11 Apr 2016 at 6:04
- Changed state: **NeedsMoreInfo**

**Comment by GoogleCodeExporter** [comment]
```
Output after running 'gcloud config set app/use_cloud_build true' :
$ gcloud preview app deploy
You are about to deploy the following modules:
 - tradeadvisor-1008/documentsdata (from [/home/alvaro/Workspace/bitbucket.org/pinho/documents-data/app.yaml])
     Deployed URL: [https://documentsdata-dot-tradeadvisor-1008.appspot.com]

Do you want to continue (Y/n)?  Y

Beginning deployment...


Using Ruby 2.3.0 as requested in the Gemfile.
Verifying that Managed VMs are enabled and ready.
Building and pushing image for module [documentsdata]
Started cloud build [04d700a6-3824-44ec-9d1b-4125e3aa6851].
To see logs in the Cloud Console: 
https://console.developers.google.com/logs?project=tradeadvisor-1008&service=clo
udbuild.googleapis.com&key1=04d700a6-3824-44ec-9d1b-4125e3aa6851&logName=project
s/tradeadvisor-1008/logs/cloudbuild
------------------------- REMOTE BUILD OUTPUT --------------------------
starting build "04d700a6-3824-44ec-9d1b-4125e3aa6851"

FETCHSOURCE
Fetching storage object: 
gs://staging.tradeadvisor-1008.appspot.com/us.gcr.io/tradeadvisor-1008/appengine
/documentsdata.20160412t084347:latest#1460463925565000
Copying 
gs://staging.tradeadvisor-1008.appspot.com/us.gcr.io/tradeadvisor-1008/appengine
/documentsdata.20160412t084347:latest#1460463925565000...
==> NOTE: You are downloading one or more large file(s), which would
run significantly faster if you enabled sliced object uploads. This
feature is enabled by default but requires that compiled crcmod be
installed (see "gsutil help crcmod").
Downloading file:///tmp/source-archive.tgz:                      0 
B/1.1Downloading file:///tmp/source-archive.tgz:                      72 
KiB/Downloading file:///tmp/source-archive.tgz:                      144 
KiBDownloading file:///tmp/source-archive.tgz:                      216 
KiBDownloading file:///tmp/source-archive.tgz:                      288 
KiBDownloading file:///tmp/source-archive.tgz:                      360 
KiBDownloading file:///tmp/source-archive.tgz:                      432 
KiBDownloading file:///tmp/source-archive.tgz:                      504 
KiBDownloading file:///tmp/source-archive.tgz:                      576 
KiBDownloading file:///tmp/source-archive.tgz:                      648 
KiBDownloading file:///tmp/source-archive.tgz:                      720 
KiBDownloading file:///tmp/source-archive.tgz:                      792 
KiBDownloading file:///tmp/source-archive.tgz:                      928 
KiBDownloading file:///tmp/source-archive.tgz:                      1.04 
MiDownloading file:///tmp/source-archive.tgz:                      1.17 
MiDownloading file:///tmp/source-archive.tgz:                      1.3 
MiBDownloading file:///tmp/source-archive.tgz:                      1.44 
MiDownloading file:///tmp/source-archive.tgz:                      1.57 
MiDownloading file:///tmp/source-archive.tgz:                      1.7 
MiBDownloading file:///tmp/source-archive.tgz:                      1.84 
MiDownloading file:///tmp/source-archive.tgz:                      1.97 
MiDownloading file:///tmp/source-archive.tgz:                      2.1 
MiBDownloading file:///tmp/source-archive.tgz:                      2.23 
MiDownloading file:///tmp/source-archive.tgz:                      2.49 
MiDownloading file:///tmp/source-archive.tgz:                      2.75 
MiDownloading file:///tmp/source-archive.tgz:                      3.01 
MiDownloading file:///tmp/source-archive.tgz:                      3.27 
MiDownloading file:///tmp/source-archive.tgz:                      3.52 
MiDownloading file:///tmp/source-archive.tgz:                      3.78 
MiDownloading file:///tmp/source-archive.tgz:                      4.04 
MiDownloading file:///tmp/source-archive.tgz:                      4.3 
MiBDownloading file:///tmp/source-archive.tgz:                      4.55 
MiDownloading file:///tmp/source-archive.tgz:                      4.81 
MiDownloading file:///tmp/source-archive.tgz:                      5.07 
MiDownloading file:///tmp/source-archive.tgz:                      5.58 
MiDownloading file:///tmp/source-archive.tgz:                      6.09 
MiDownloading file:///tmp/source-archive.tgz:                      6.59 
MiDownloading file:///tmp/source-archive.tgz:                      7.1 
MiBDownloading file:///tmp/source-archive.tgz:                      7.61 
MiDownloading file:///tmp/source-archive.tgz:                      8.12 
MiDownloading file:///tmp/source-archive.tgz:                      8.63 
MiDownloading file:///tmp/source-archive.tgz:                      9.13 
MiDownloading file:///tmp/source-archive.tgz:                      9.64 
MiDownloading file:///tmp/source-archive.tgz:                      10.15 
MDownloading file:///tmp/source-archive.tgz:                      10.66 
MDownloading file:///tmp/source-archive.tgz:                      11.66 
MDownloading file:///tmp/source-archive.tgz:                      12.67 
MDownloading file:///tmp/source-archive.tgz:                      13.68 
MDownloading file:///tmp/source-archive.tgz:                      14.69 
MDownloading file:///tmp/source-archive.tgz:                      15.7 
MiDownloading file:///tmp/source-archive.tgz:                      16.7 
MiDownloading file:///tmp/source-archive.tgz:                      17.71 
MDownloading file:///tmp/source-archive.tgz:                      18.72 
MDownloading file:///tmp/source-archive.tgz:                      19.73 
MDownloading file:///tmp/source-archive.tgz:                      20.73 
MDownloading file:///tmp/source-archive.tgz:                      21.74 
MDownloading file:///tmp/source-archive.tgz:                      23.75 
MDownloading file:///tmp/source-archive.tgz:                      25.76 
MDownloading file:///tmp/source-archive.tgz:                      27.77 
MDownloading file:///tmp/source-archive.tgz:                      29.77 
MDownloading file:///tmp/source-archive.tgz:                      31.78 
MDownloading file:///tmp/source-archive.tgz:                      33.79 
MDownloading file:///tmp/source-archive.tgz:                      35.8 
MiDownloading file:///tmp/source-archive.tgz:                      37.8 
MiDownloading file:///tmp/source-archive.tgz:                      39.81 
MDownloading file:///tmp/source-archive.tgz:                      41.82 
MDownloading file:///tmp/source-archive.tgz:                      43.83 
MDownloading file:///tmp/source-archive.tgz:                      47.84 
MDownloading file:///tmp/source-archive.tgz:                      51.84 
MDownloading file:///tmp/source-archive.tgz:                      55.85 
MDownloading file:///tmp/source-archive.tgz:                      59.86 
MDownloading file:///tmp/source-archive.tgz:                      63.87 
MDownloading file:///tmp/source-archive.tgz:                      67.88 
MDownloading file:///tmp/source-archive.tgz:                      71.88 
MDownloading file:///tmp/source-archive.tgz:                      75.89 
MDownloading file:///tmp/source-archive.tgz:                      79.9 
MiDownloading file:///tmp/source-archive.tgz:                      83.91 
MDownloading file:///tmp/source-archive.tgz:                      87.91 
MDownloading file:///tmp/source-archive.tgz:                      95.92 
MDownloading file:///tmp/source-archive.tgz:                      103.93 
Downloading file:///tmp/source-archive.tgz:                      111.94 
Downloading file:///tmp/source-archive.tgz:                      119.95 
Downloading file:///tmp/source-archive.tgz:                      127.95 
Downloading file:///tmp/source-archive.tgz:                      135.96 
Downloading file:///tmp/source-archive.tgz:                      143.97 
Downloading file:///tmp/source-archive.tgz:                      151.98 
Downloading file:///tmp/source-archive.tgz:                      159.98 
Downloading file:///tmp/source-archive.tgz:                      167.99 
Downloading file:///tmp/source-archive.tgz:                      176 
MiBDownloading file:///tmp/source-archive.tgz:                      192.01 
Downloading file:///tmp/source-archive.tgz:                      208.02 
Downloading file:///tmp/source-archive.tgz:                      224.02 
Downloading file:///tmp/source-archive.tgz:                      240.03 
Downloading file:///tmp/source-archive.tgz:                      256.04 
Downloading file:///tmp/source-archive.tgz:                      272.05 
Downloading file:///tmp/source-archive.tgz:                      288.05 
Downloading file:///tmp/source-archive.tgz:                      304.06 
Downloading file:///tmp/source-archive.tgz:                      320.07 
Downloading file:///tmp/source-archive.tgz:                      336.08 
Downloading file:///tmp/source-archive.tgz:                      352.09 
Downloading file:///tmp/source-archive.tgz:                      384.09 
Downloading file:///tmp/source-archive.tgz:                      416.1 
MDownloading file:///tmp/source-archive.tgz:                      448.11 
Downloading file:///tmp/source-archive.tgz:                      480.12 
Downloading file:///tmp/source-archive.tgz:                      512.13 
Downloading file:///tmp/source-archive.tgz:                      544.13 
Downloading file:///tmp/source-archive.tgz:                      576.14 
Downloading file:///tmp/source-archive.tgz:                      608.15 
Downloading file:///tmp/source-archive.tgz:                      640.16 
Downloading file:///tmp/source-archive.tgz:                      672.16 
Downloading file:///tmp/source-archive.tgz:                      704.17 
Downloading file:///tmp/source-archive.tgz:                      768.18 
Downloading file:///tmp/source-archive.tgz:                      832.19 
Downloading file:///tmp/source-archive.tgz:                      896.2 
MDownloading file:///tmp/source-archive.tgz:                      960.2 
MDownloading file:///tmp/source-archive.tgz:                      1 
GiB/1Downloading file:///tmp/source-archive.tgz:                      1.06 
GiDownloading file:///tmp/source-archive.tgz:                      1.13 
GiDownloading file:///tmp/source-archive.tgz:                      1.16 
GiB/1.16 GiB    
FETCHBUILDER
BUILD
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
Sending build context to Docker daemon 3.415 GB
Step 1 : FROM gcr.io/google_appengine/ruby
 ---> 3e6d0d6d0575
Step 2 : RUN cd /rbenv/plugins/ruby-build &&     git pull &&     rbenv install 
-s 2.3.0 &&     rbenv global 2.3.0 &&     gem install -q --no-rdoc --no-ri 
bundler --version 1.11.2 &&     gem install -q --no-rdoc --no-ri foreman 
--version 0.78.0
 ---> Running in bd0a4b6dde61
From https://github.com/sstephenson/ruby-build
   522f3ba..d7668be  master     -> origin/master
 * [new tag]         v20160330  -> v20160330
Updating 522f3ba..d7668be
Fast-forward
 bin/ruby-build            | 2 +-
 share/ruby-build/2.1.10   | 2 ++
 share/ruby-build/2.1.9    | 2 ++
 share/ruby-build/rbx-3.20 | 3 +++
 share/ruby-build/rbx-3.21 | 3 +++
 share/ruby-build/rbx-3.22 | 3 +++
 share/ruby-build/rbx-3.23 | 3 +++
 share/ruby-build/rbx-3.24 | 3 +++
 share/ruby-build/rbx-3.25 | 3 +++
 9 files changed, 23 insertions(+), 1 deletion(-)
 create mode 100644 share/ruby-build/2.1.10
 create mode 100644 share/ruby-build/2.1.9
 create mode 100644 share/ruby-build/rbx-3.20
 create mode 100644 share/ruby-build/rbx-3.21
 create mode 100644 share/ruby-build/rbx-3.22
 create mode 100644 share/ruby-build/rbx-3.23
 create mode 100644 share/ruby-build/rbx-3.24
 create mode 100644 share/ruby-build/rbx-3.25
Successfully installed bundler-1.11.2
1 gem installed
Successfully installed foreman-0.78.0
1 gem installed
 ---> 591fb5f5a7e6
Removing intermediate container bd0a4b6dde61
Step 3 : ENV RBENV_VERSION 2.3.0
 ---> Running in bfdcf2bcc1ee
 ---> 949c65d76013
Removing intermediate container bfdcf2bcc1ee
Step 4 : COPY Gemfile Gemfile.lock /app/
 ---> 7979e7d8b90e
Removing intermediate container c0a7fe035019
Step 5 : RUN bundle install --deployment && rbenv rehash
 ---> Running in 60bd9ae01f93
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching git://github.com/elasticsearch/elasticsearch-ruby.git
Installing rake 11.1.2
Installing CFPropertyList 2.3.2
Installing i18n 0.7.0
Using json 1.8.3
Installing minitest 5.8.4
Installing thread_safe 0.3.5
Installing builder 3.2.2
Installing erubis 2.7.0
Installing mini_portile2 2.0.0
Installing rack 1.6.4
Installing mime-types-data 3.2016.0221
Installing arel 6.0.3
Installing addressable 2.4.0
Installing amq-protocol 1.9.2
Installing coderay 1.1.1
Installing debug_inspector 0.0.2 with native extensions
Installing byebug 8.2.4 with native extensions
Installing hitimes 1.2.3 with native extensions
Installing coffee-script-source 1.10.0
Installing execjs 2.6.0
Installing thor 0.19.1
Installing colored 1.2
Installing concurrent-ruby 1.0.1
Installing connection_pool 2.2.0
Installing multi_json 1.11.2
Installing multipart-post 2.0.0
Installing excon 0.49.0
Installing formatador 0.2.5
Installing ipaddress 0.8.3
Installing xml-simple 1.1.5
Installing inflecto 0.0.2
Installing trollop 2.1.2
Installing multi_xml 0.5.5
Installing httpclient 2.7.1
Installing kgio 2.10.0 with native extensions
Installing mdb 0.3.2
Installing method_source 0.8.2
Installing os 0.9.6
Installing rubyzip 1.1.7
Installing net-http-persistent 2.9.4
Installing orm_adapter 0.5.0
Installing parallel 1.8.0
Installing pg 0.18.4 with native extensions
Installing slop 3.6.0
Using bundler 1.11.2
Installing raindrops 0.16.0 with native extensions
Installing redis 3.2.2
Installing retryable 2.0.3
Installing sass 3.4.22
Installing tilt 2.0.2
Installing fission 0.5.0
Installing rdoc 4.2.2
Installing tzinfo 1.2.2
Installing nokogiri 1.6.7.2 with native extensions
Installing rack-test 0.6.3
Installing mime-types 3.0
Installing bunny 1.7.1
Installing better_errors 2.1.1
Installing binding_of_caller 0.7.2 with native extensions
Installing timers 4.1.1
Installing coffee-script 2.4.1
Installing uglifier 3.0.0
Installing figaro 1.1.1
Installing foreman 0.78.0
Installing sprockets 3.6.0
Using elasticsearch-api 1.0.17 from 
git://github.com/elasticsearch/elasticsearch-ruby.git (at master@47258c9)
Installing faraday 0.9.2
Installing fog-core 1.37.0
Installing httparty 0.13.7
Installing zip-zip 0.3
Installing pry 0.10.3
Installing unicorn 5.1.0 with native extensions
Installing redis-namespace 1.5.2
Installing sdoc 0.4.1
Installing activesupport 4.2.6
Installing loofah 2.0.3
Installing xpath 2.0.0
Installing rbvmomi 1.8.2
Installing mail 2.6.4
Installing celluloid-essentials 0.20.5
Installing celluloid-extras 0.20.5
Installing celluloid-fsm 0.20.5
Installing celluloid-pool 0.20.5
Installing celluloid-supervision 0.20.5
Using elasticsearch-transport 1.0.17 from 
git://github.com/elasticsearch/elasticsearch-ruby.git (at master@47258c9)
Installing faraday_middleware 0.10.0
Installing fog-json 1.0.2
Installing fog-xml 0.1.2
Installing fog-local 0.3.0
Installing fog-vmfusion 0.1.0
Installing neo4j-rake_tasks 0.4.2
Installing unicorn-rails 2.2.0
Installing rails-deprecated_sanitizer 1.0.3
Installing globalid 0.3.6
Installing activemodel 4.2.6
Installing jbuilder 2.4.1
Installing rails-html-sanitizer 1.0.3
Installing capybara 2.7.0
Installing fog-vsphere 0.6.3
Installing celluloid 0.17.3
Using elasticsearch 1.0.17 from 
git://github.com/elasticsearch/elasticsearch-ruby.git (at master@47258c9)
Installing faraday_middleware-multi_json 0.0.6
Installing fog-aliyun 0.1.0
Installing fog-brightbox 0.10.1
Installing fog-sakuracloud 1.7.5
Installing fog-serverlove 0.1.2
Installing fog-softlayer 1.1.0
Installing fog-storm_on_demand 0.1.1
Installing fog-atmos 0.1.0
Installing fog-aws 0.9.2
Installing fog-cloudatcost 0.1.2
Installing fog-dynect 0.0.3
Installing fog-ecloud 0.3.0
Installing fog-google 0.1.0
Installing fog-openstack 0.1.2
Installing fog-powerdns 0.1.1
Installing fog-profitbricks 0.0.5
Installing fog-rackspace 0.1.1
Installing fog-radosgw 0.0.5
Installing fog-riakcs 0.1.0
Installing fog-terremark 0.1.0
Installing fog-voxel 0.1.0
Installing fog-xenserver 0.2.3
Installing rails-dom-testing 1.0.7
Installing activejob 4.2.6
Installing activerecord 4.2.6
Installing show_me_the_cookies 3.1.0
Installing sidekiq 3.5.4
Installing neo4j-core 6.1.2
Installing fog 1.38.0
Installing actionview 4.2.6
Installing roundhousekiq 1.0.0
Installing neo4j 7.0.2
Installing actionpack 4.2.6
Installing actionmailer 4.2.6
Installing railties 4.2.6
Installing sprockets-rails 3.0.4
Installing coffee-rails 4.1.1
Installing jquery-rails 4.1.1
Installing rails 4.2.6
Installing sass-rails 5.0.4
Installing web-console 2.3.0
Installing turbolinks 2.5.3
Bundle complete! 30 Gemfile dependencies, 143 gems now installed.
Bundled gems are installed into ./vendor/bundle.
Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
Post-install message from httparty:
When you HTTParty, you must party hard!
 ---> e84ecf9110ea
Removing intermediate container 60bd9ae01f93
Step 6 : COPY . /app/
ERROR: (gcloud.preview.app.deploy) Error Response: [4] DEADLINE_EXCEEDED

```

Original comment by `alvaro.i...@pinho.com.br` on 12 Apr 2016 at 12:57

**Comment by GoogleCodeExporter** [comment]
```
Ahh, it sounds as though you're exceeding the Cloud Build timeout. You can 
increase it from the default (10 minutes) by running e.g. `gcloud config set 
app/cloud_build_timeout 2000`.

However, usually this indicates that your Dockerfile is doing too much. You 
should consider doing most of the heavy lifting (gem installation, etc.) in a 
base image, and having your app Dockerfile derive from that.
```

Original comment by `z...@google.com` on 12 Apr 2016 at 4:46
