### ISSUE TITLE
Unable to deploy using Nodejs 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#717]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "googlecloudsdk/gcloud_main.py", line 169, in main
    gcloud_cli.Execute()
  File "googlecloudsdk/calliope/cli.py", line 654, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "googlecloudsdk/calliope/backend.py", line 1376, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 509, in Run
    config_cleanup)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 215, in BuildAndPushDockerImages
    info.file, docker_client, image_name)
  File "googlecloudsdk/api_lib/app/deploy_command_util.py", line 289, in BuildAndPushDockerImage
    image.Build(docker_client)
  File "googlecloudsdk/api_lib/app/docker_image.py", line 117, in Build
    for line in build_res:
  File "third_party/docker/docker/client.py", line 213, in _stream_helper
    data = reader.read(1)
  File "third_party/requests/packages/urllib3/response.py", line 231, in read
    raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', 
IncompleteRead(0 bytes read))

Installation information:

Google Cloud SDK [101.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.5 (default, Mar  9 2014, 22:15:05)  [GCC 4.2.1 Compatible 
Apple LLVM 5.0 (clang-500.0.68)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

[output truncated]

```

Original issue reported on code.google.com by `m.y.yang...@gmail.com` on 9 Apr 2016 at 11:55

**Comment by GoogleCodeExporter** [comment]
```
Please try again with `gcloud config set app/use_cloud_build` set to false. 
This will disable direct use of docker-py, which doesn't respect gcloud-wide 
proxy settings.
```

Original comment by `z...@google.com` on 11 Apr 2016 at 1:49
- Changed state: **NeedsMoreInfo**
