### ISSUE TITLE
source-context.json is required now?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#746]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?

I upgraded from gcloud 104.0.0 to 105.0.0. I saw this in the release notes: 
"File uploads during gcloud preview app deploy have been improved. If you have 
any trouble, you can revert to the old behavior with gcloud config set 
app/use_gsutil true."


What is the expected output? What do you see instead?

Normally it pushes my appengine project in 3.5 minutes. Now I got a 16m+ 
runtime followed by this crash on a missing source-context.json (which was 
never required before...but maybe is now? I don't see any release notes about 
that though)

Please provide any additional information below.


Trace:
googlecloudsdk/gcloud_main.py:169
 gcloud_cli.Execute()
googlecloudsdk/calliope/cli.py:654
 result = args.cmd_func(cli=self, args=ar...
googlecloudsdk/calliope/backend.py:1401
 resources = command_instance.Run(args)
surface/preview/app/deploy.py:522
 storage_client)
googlecloudsdk/api_app/deploy_app_command_util.py:170
 _UploadFiles(files_to_upload, bucket_ref...
googlecloudsdk/api_app/deploy_app_command_util.py:113
 args=(bucket_ref, path, sha1_hash, stora...
googlecloudsdk/core/util/retry.py:176
 TryFunc, should_retry_if=should_retry, s...
googlecloudsdk/core/util/retry.py:234
 self._RaiseIfStop(result, state)
googlecloudsdk/core/util/retry.py:109
 raise MaxRetrialsException('Reached', re...
MaxRetrialsException: last_result=(None, (<class 
'googlecloudsdk.calliope.exceptions.BadFileException'>, 
BadFileException('[/Users/lambert/Projects/dancedeets/source-context.json] not 
found or not accessible',), <traceback object at 0x1049c95f0>)), 
last_retrial=3, time_passed_ms=3,time_to_wait=0Installation information:

Google Cloud SDK [105.0.0]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.11 (default, Jan 22 2016, 08:29:18)  [GCC 4.2.1 Compatible 
Apple LLVM 7.0.2 (clang-700.1.81)]]
Python Location: 
[/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resour
ces/Python.app/Contents/MacOS/Python]
Site Packages: [Disabled]

I ran with "--verbosity debug"...here is the end of that log:
DEBUG: Uploading 
[/Users/lambert/Projects/dancedeets/lib/pytz/zoneinfo/Africa/Libreville] to 
[6fa3682d860ca2a88e2ef1fd01e081138b945221]
INFO: Uploading 
[/Users/lambert/Projects/dancedeets/lib/pytz/zoneinfo/Africa/Libreville] to 
[6fa3682d860ca2a88e2ef1fd01e081138b945221]
DEBUG: Uploading 
[/Users/lambert/Projects/dancedeets/lib/flask_admin/translations/nl/LC_MESSAGES/
admin.mo] to [6fc86de25faf2ca77f576dffe83e05c45e27a88a]
INFO: Uploading 
[/Users/lambert/Projects/dancedeets/lib/flask_admin/translations/nl/LC_MESSAGES/
admin.mo] to [6fc86de25faf2ca77f576dffe83e05c45e27a88a]
DEBUG: Uploading 
[/Users/lambert/Projects/dancedeets/lib/lxml/includes/lxml-version.h] to 
[6fd38831cde83f74fb87b20fa3b03bf82f88929d]
INFO: Uploading 
[/Users/lambert/Projects/dancedeets/lib/lxml/includes/lxml-version.h] to 
[6fd38831cde83f74fb87b20fa3b03bf82f88929d]
DEBUG: Uploading [/Users/lambert/Projects/dancedeets/source-context.json] to 
[6fda68692457d44a2ee6476c85f0ff093ad21748]
DEBUG: last_result=(None, (<class 
'googlecloudsdk.calliope.exceptions.BadFileException'>, 
BadFileException('[/Users/lambert/Projects/dancedeets/source-context.json] not 
found or not accessible',), <traceback object at 0x1049c95f0>)), 
last_retrial=3, time_passed_ms=3,time_to_wait=0
Traceback (most recent call last):
  File "/Users/lambert/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 654, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/lambert/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1401, in Run
    resources = command_instance.Run(args)
  File "/Users/lambert/google-cloud-sdk/lib/surface/preview/app/deploy.py", line 522, in Run
    storage_client)
  File "/Users/lambert/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/deploy_app_command_util.py", line 170, in CopyFilesToCodeBucketNoGsUtil
    _UploadFiles(files_to_upload, bucket_ref, storage_client)
  File "/Users/lambert/google-cloud-sdk/lib/googlecloudsdk/api_lib/app/deploy_app_command_util.py", line 113, in _UploadFiles
    args=(bucket_ref, path, sha1_hash, storage_client)
  File "/Users/lambert/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 176, in RetryOnException
    TryFunc, should_retry_if=should_retry, sleep_ms=sleep_ms)
  File "/Users/lambert/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 234, in RetryOnResult
    self._RaiseIfStop(result, state)
  File "/Users/lambert/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 109, in _RaiseIfStop
    raise MaxRetrialsException('Reached', result, state)
MaxRetrialsException: last_result=(None, (<class 
'googlecloudsdk.calliope.exceptions.BadFileException'>, 
BadFileException('[/Users/lambert/Projects/dancedeets/source-context.json] not 
found or not accessible',), <traceback object at 0x1049c95f0>)), 
last_retrial=3, time_passed_ms=3,time_to_wait=0
ERROR: gcloud crashed (MaxRetrialsException): last_result=(None, (<class 
'googlecloudsdk.calliope.exceptions.BadFileException'>, 
BadFileException('[/Users/lambert/Projects/dancedeets/source-context.json] not 
found or not accessible',), <traceback object at 0x1049c95f0>)), 
last_retrial=3, time_passed_ms=3,tim



Other information:
Installation Root: [/Users/lambert/google-cloud-sdk]
Installed Components:
  core: [2016.04.11]
  app-engine-python: [1.9.35]
  core-nix: [2016.03.28]
  kubectl: []
  app-engine-java: [1.9.34]
  gcloud: []
  gsutil-nix: [4.18]
  gsutil: [4.18]
  bq: [2.0.24]
  bq-nix: [2.0.24]
  kubectl-darwin-x86_64: [1.2.0]
System PATH: 
[/Users/lambert/.venvburrito/bin:/Users/lambert/google-cloud-sdk/bin:/Users/lamb
ert/bin:/Users/lambert/Library/Python/2.7/bin/:/usr/local/bin:/usr/bin:/bin:/usr
/sbin:/sbin:/opt/X11/bin]
Cloud SDK on PATH: [True]

Installation Properties: [/Users/lambert/google-cloud-sdk/properties]
User Config Directory: [/Users/lambert/.config/gcloud]
Active Configuration Name: [test]
Active Configuration Path: 
[/Users/lambert/.config/gcloud/configurations/config_test]

Account: [mlambert@gmail.com]
Project: [dancedeets-hrd]

Current Properties:
  [core]
    project: [dancedeets-hrd]
    account: [mlambert@gmail.com]
    disable_usage_reporting: [False]
  [app]
    suppress_change_warning: [true]
  [compute]
    zone: [us-central1-b]

Logs Directory: [/Users/lambert/.config/gcloud/logs]
Last Log File: 
[/Users/lambert/.config/gcloud/logs/2016.04.16/05.32.42.277920.log]

```

Original issue reported on code.google.com by `mlamb...@gmail.com` on 16 Apr 2016 at 3:04
- Merged into: #727

**Comment by GoogleCodeExporter** [comment]
```
Running "gcloud config set app/use_gsutil true" appears to fix my problem. Both 
the crash, as well as the 16minute deploy times (which are now just 3 minutees 
again).
```

Original comment by `mlamb...@gmail.com` on 16 Apr 2016 at 3:07

**Comment by GoogleCodeExporter** [comment]
Original comment by `z...@google.com` on 17 Apr 2016 at 1:31
- Changed state: **Duplicate**
