### ISSUE TITLE
gcloud preview app deploy crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [venf2k/google-cloud-sdk#751]
```
Issue running command [gcloud preview app deploy].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Traceback (most recent call last):
  File "calliope/cli.py", line 605, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "calliope/backend.py", line 1228, in Run
    resources = command_instance.Run(args)
  File "surface/preview/app/deploy.py", line 296, in Run
    images.get(module))
  File "api_lib/app/appengine_api_client.py", line 76, in DeployModule
    return operations.WaitForOperation(self.client.apps_operations, operation)
  File "api_lib/app/api/operations.py", line 54, in WaitForOperation
    encoding.MessageToPyValue(completed_operation.error)))
  File "api_lib/app/api/requests.py", line 57, in ExtractErrorMessage
    message=error_details.get('message', '')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd7' in position 
118: ordinal not in range(128)

Installation information:

Google Cloud SDK [0.9.86]

Platform: [Mac OS X, x86_64]
Python Version: [2.7.10 (default, Jul 14 2015, 19:46:27)  [GCC 4.2.1 Compatible 
Apple LLVM 6.0 (clang-600.0.39)]]
Python Location: [/usr/bin/python]
Site Packages: [Disabled]

Installation Root: [/Users/ravi/google-cloud-sdk]
Installed Components:
  core: [2015.11.06]
  core-nix: [2015.09.03]
  gcloud: []
  gsutil-nix: [4.14]
  gsutil: [4.15]
  bq: [2.0.18]
  bq-nix: [2.0.18]
[output truncated]

```

Original issue reported on code.google.com by `ravinara...@gmail.com` on 17 Apr 2016 at 3:05

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your feedback and sorry about the delayed response.

Can you upgrade to the latest Cloud SDK and try this again?
```

Original comment by `vil...@google.com` on 21 Apr 2016 at 4:28
- Changed state: **NeedsMoreInfo**
